---
spring:
  profiles: cloud

catalog:
  services:
    - id: cloudkarafka
      name: cloudkarafka
      description: Message streaming as a Service
      bindable: true
      plan-updatable: true
      tags:
        - kafka
        - broker
      service-settings:
        service-type: kafka
      metadata:
        displayName: cloudkarafka
        imageUrl: https://lh4.googleusercontent.com/ag1iBij6ggnLYP0YODI4JnculNLdE0DI6HUlfvQ9iFpIvsKxkf32jkPLwvV5CCgbUWPzqFkyOmEUSW8=w3058-h1612
        longDescription: Decouple, distribute and scale your applications with the speed of CloudKarafka
        providerDisplayName: CloudKarafka
        documentationUrl: https://github.com/ipolyzos/cloudkarafka-broker
        supportUrl: http://www.cloudkarafka.com/support.html
      plans:
        - id: ducky_076b82374bf5411bb188018b0e5b
          name: Developer Duck
          description: For Development, Shared
          service-settings:
            quota:
              limit: 3
              warn: 2
          free: true
          metadata:
            costs:
              - amount:
                  usd: 0.0
                unit: MONTHLY
            bullets:
              - Shared cluster
              - Max 5 topics
              - Max 10MB data per topic
              - Max 28 days retention
        - id: mouse-1_35d035c9a3964599a5de5952b509
          name: Mini Mouse x 1
          description: For Hobby Apps, 1 node
          service-settings:
            quota:
              limit: 5
              warn: 4
          metadata:
            costs:
              - amount:
                  usd: 99.0
                unit: MONTHLY
            bullets:
             - Available in 1, 3, 5 or 7 nodes
             - Zookeeper on all nodes
             - 1 core per node
             - 2 GB RAM per node
             - 25GB disk per node
             - Unlimited log retention and compaction
        - id: mouse-3_35d035c9a3964599a5de5952b509
          name: Mini Mouse x 3
          description: For Hobby Apps, 3 nodes
          service-settings:
            quota:
              limit: 5
              warn: 4
          metadata:
            costs:
              - amount:
                  usd: 297.0
                unit: MONTHLY
            bullets:
             - Available in 1, 3, 5 or 7 nodes
             - Zookeeper on all nodes
             - 1 core per node
             - 2 GB RAM per node
             - 25GB disk per node
             - Unlimited log retention and compaction
        - id: mouse-5_35d035c9a3964599a5de5952b509
          name: Mini Mouse x 5
          description: For Hobby Apps, 5 nodes
          service-settings:
            quota:
              limit: 5
              warn: 4
          metadata:
            costs:
              - amount:
                  usd: 495.0
                unit: MONTHLY
            bullets:
             - Available in 1, 3, 5 or 7 nodes
             - Zookeeper on all nodes
             - 1 core per node
             - 2 GB RAM per node
             - 25GB disk per node
             - Unlimited log retention and compaction
        - id: mouse-7_35d035c9a3964599a5de5952b509
          name: Mini Mouse x 7
          description: For Hobby Apps, 7 nodes
          service-settings:
            quota:
              limit: 5
              warn: 4
          metadata:
            costs:
              - amount:
                  usd: 693.0
                unit: MONTHLY
            bullets:
             - Available in 1, 3, 5 or 7 nodes
             - Zookeeper on all nodes
             - 1 core per node
             - 2 GB RAM per node
             - 25GB disk per node
             - Unlimited log retention and compaction
        - id: bat-1_63e6c39a05754d21a251b9ba7b35
          name: Bouncying Bat x 1
          description: Small size, 1 node
          service-settings:
            quota:
              limit: 5
              warn: 4
          metadata:
            costs:
              - amount:
                  usd: 175.0
                unit: MONTHLY
            bullets:
              - Available in 1, 3, 5 or 7 nodes
              - Zookeeper on all nodes
              - 2 cores per node
              - 4 GB RAM per node
              - 500GB disk per node
              - Unlimited log retention and compaction
        - id: bat-3_63e6c39a05754d21a251b9ba7b35
          name: Bouncying Bat x 3
          description: Small size, 3 nodes
          service-settings:
            quota:
              limit: 5
              warn: 4
          metadata:
            costs:
              - amount:
                  usd: 525.0
                unit: MONTHLY
            bullets:
              - Available in 1, 3, 5 or 7 nodes
              - Zookeeper on all nodes
              - 2 cores per node
              - 4 GB RAM per node
              - 500GB disk per node
              - Unlimited log retention and compaction
        - id: bat-5_63e6c39a05754d21a251b9ba7b35
          name: Bouncying Bat x 5
          description: Small size, 5 nodes
          service-settings:
            quota:
              limit: 5
              warn: 4
          metadata:
            costs:
              - amount:
                  usd: 875.0
                unit: MONTHLY
            bullets:
              - Available in 1, 3, 5 or 7 nodes
              - Zookeeper on all nodes
              - 2 cores per node
              - 4 GB RAM per node
              - 500GB disk per node
              - Unlimited log retention and compaction
        - id: bat-7_63e6c39a05754d21a251b9ba7b35
          name: Bouncying Bat x 7
          description: Small size, 7 nodes
          service-settings:
            quota:
              limit: 5
              warn: 4
          metadata:
            costs:
              - amount:
                  usd: 1225.0
                unit: MONTHLY
            bullets:
              - Available in 1, 3, 5 or 7 nodes
              - Zookeeper on all nodes
              - 2 cores per node
              - 4 GB RAM per node
              - 500GB disk per node
              - Unlimited log retention and compaction
        - id: fox-1_63e6c39a05754d21a251b9ba7b3
          name: Fast Fox x 1
          description: Medium size, 1 node
          service-settings:
            quota:
              limit: 5
              warn: 4
          metadata:
            costs:
              - amount:
                  usd: 335.0
                unit: MONTHLY
            bullets:
              - Available in 1, 3, 5 or 7 nodes
              - Zookeeper on all nodes
              - 2 cores per node
              - 8 GB RAM per node
              - 1000GB disk per node
              - Unlimited log retention and compaction
        - id: fox-3_63e6c39a05754d21a251b9ba7b3
          name: Fast Fox x 3
          description: Medium size, 3 nodes
          service-settings:
            quota:
              limit: 5
              warn: 4
          metadata:
            costs:
              - amount:
                  usd: 1005.0
                unit: MONTHLY
            bullets:
              - Available in 1, 3, 5 or 7 nodes
              - Zookeeper on all nodes
              - 2 cores per node
              - 8 GB RAM per node
              - 1000GB disk per node
              - Unlimited log retention and compaction
        - id: fox-5_63e6c39a05754d21a251b9ba7b3
          name: Fast Fox x 5
          description: Medium size, 5 nodes
          service-settings:
            quota:
              limit: 5
              warn: 4
          metadata:
            costs:
              - amount:
                  usd: 1675.0
                unit: MONTHLY
            bullets:
              - Available in 1, 3, 5 or 7 nodes
              - Zookeeper on all nodes
              - 2 cores per node
              - 8 GB RAM per node
              - 1000GB disk per node
              - Unlimited log retention and compaction
        - id: fox-7_63e6c39a05754d21a251b9ba7b3
          name: Fast Fox x 7
          description: Medium size, 7 nodes
          service-settings:
            quota:
              limit: 5
              warn: 4
          metadata:
            costs:
              - amount:
                  usd: 2345.0
                unit: MONTHLY
            bullets:
              - Available in 1, 3, 5 or 7 nodes
              - Zookeeper on all nodes
              - 2 cores per node
              - 8 GB RAM per node
              - 1000GB disk per node
              - Unlimited log retention and compaction
        - id: lion-1_f69f8eec59934c2c8e2bc55888f9
          name: Large Lion x 1
          description: Large size, 1 node
          service-settings:
            quota:
              limit: 5
              warn: 4
          metadata:
            costs:
              - amount:
                  usd: 750.0
                unit: MONTHLY
            bullets:
              - Available in 1, 3, 5 or 7 nodes
              - Zookeeper on all nodes
              - 4 cores per node
              - 16 GB RAM per node
              - 2000GB disk per node
              - Unlimited log retention and compaction
        - id: lion-3_f69f8eec59934c2c8e2bc55888f9
          name: Large Lion x 3
          description: Large size, 3 nodes
          service-settings:
            quota:
              limit: 5
              warn: 4
          metadata:
            costs:
              - amount:
                  usd: 2250.0
                unit: MONTHLY
            bullets:
              - Available in 1, 3, 5 or 7 nodes
              - Zookeeper on all nodes
              - 4 cores per node
              - 16 GB RAM per node
              - 2000GB disk per node
              - Unlimited log retention and compaction
        - id: lion-5_f69f8eec59934c2c8e2bc55888f9
          name: Large Lion x 5
          description: Large size, 5 nodes
          service-settings:
            quota:
              limit: 5
              warn: 4
          metadata:
            costs:
              - amount:
                  usd: 3750.0
                unit: MONTHLY
            bullets:
              - Available in 1, 3, 5 or 7 nodes
              - Zookeeper on all nodes
              - 4 cores per node
              - 16 GB RAM per node
              - 2000GB disk per node
              - Unlimited log retention and compaction
        - id: lion-7_f69f8eec59934c2c8e2bc55888f9
          name: Large Lion x 7
          description: Large size, 7 nodes
          service-settings:
            quota:
              limit: 5
              warn: 4
          metadata:
            costs:
              - amount:
                  usd: 3750.0
                unit: MONTHLY
            bullets:
              - Available in 1, 3, 5 or 7 nodes
              - Zookeeper on all nodes
              - 4 cores per node
              - 16 GB RAM per node
              - 2000GB disk per node
              - Unlimited log retention and compaction